#!/bin/sh
### BEGIN INIT INFO
# Provides:          vx-rule-profile-disposable
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     S
# Default-Stop:
### END INIT INFO

set -e

PATH=/usr/bin:/usr/sbin:/bin:/sbin

case "$1" in
  start)
    vx-rule-profile-disposable
  ;;

  restart|reload|force-reload)
    :
  ;;

  stop)
    :
  ;;
esac
